### ISSUE TITLE
Requesting information about usage in long-reads

### ISSUE THREAD

**Issue by sagnikbanerjee15** [splicebox/PsiCLASS#36] opened 2024-06-14 15:15 UTC
Hello,

Is it possible for PsiClass to be executed on long-reads generated from PacBio and/or Nanopore? If not, is it possible to make quick modifications to the code to adapt to long reads?

Thank you,
Sagnik

**Comment by mourisl** [comment] 2024-06-14 15:21
I think it should be able to handle the long-read alignment BAM file. If the intron splice site is more or less accurate, it should be fine. The potential issue I can think of from the long read is that a read can span multiple exons, and by default, PsiCLASS stores at most 127 exons for an alignment, and may crash when it goes above. You can change the threshold by increase the threshold here https://github.com/splicebox/PsiCLASS/blob/master/defs.h#L6 .

**Comment by sagnikbanerjee15** [comment] 2024-06-15 00:17
Thank you for the quick reply. I aligned the long reads using minimap2 and am using addXS but I am entering into a segmentation fault. I have tried increasing the max number of alignments to 255 but that has not solved the problem.

Thank you.

**Comment by cynthiawebster** [comment] 2024-11-01 23:43
Hi @sagnikbanerjee15 - Were you able to find a workaround in the code? I am running into the same issue with PacBio long reads aligned w/ minimap2. Thanks!

**Comment by mourisl** [comment] 2024-11-01 23:46
Which step PsiCLASS failed? Could you please share the running log?

**Comment by cynthiawebster** [comment] 2024-11-02 15:46
Hi @mourisl - 
I kept the run simple: `psiclass -b lr_CDO11_isoseq.bam -p 8 `

This is the log:
```
Command output:
  /softwares/PsiCLASS-1.0.3/junc lr_CDO11_isoseq.bam -a  > ./splice/psiclass_bam_0.raw_splice
  /softwares/PsiCLASS-1.0.3/trust-splice ./splice/psiclass_splice.list lr_CDO11_isoseq.bam  > ./splice/psiclass_bam.trusted_splice

Command error:
  Segmentation fault (core dumped)
  Thread 1 terminated abnormally: Terminated
  Terminated
```
Looking in the `splice` directory, I can see that `psiclass_bam_0.raw_splice` was generated -- but one of the chromosome names gets cut at the tail end of the file resulting in `Unknown genome name:`  in the `psiclass_bam.trusted_splice`.

**Comment by mbeavitt** [comment] 2024-11-07 16:55
Hi, I'm currently trying to debug the same issue. Thank you for identifying junc as the issue, I am able to reproduce the same segfault issue. Raising the LINE_SIZE macro produces a different error:

```
> ./junc long_reads.bam
# [ many lines of output not shown]
chr02 21165375 21165445 3 ? 3 0 96 0
chr02 21165526 21165618 3 ? 3 0 96 0
chr02 21165731 21165831 3 ? 3 0 96 0
chr02 21165931 21166024 3 ? 3 0 96 0
chr02 21166113 21166495 3 ? 3 0 96 0
chr02 21170335 21170425 3 ? 3 0 100 0
chr02 21170694 21170771 3 ? 3 0 100 0
chr02 21170861 21170952 3 ? 3 0 100 0
chr02 21171061 21171150 3 ? 3 0 100 0
chr02 21171419 21171871 3 ? 3 0 100 0
*** stack smashing detected ***: terminated
Aborted (core dumped)
```
I'll be actively debugging this, and will update with any findings. If you'd like to repro, here is the bam file I used: https://drive.google.com/drive/folders/1OXNeyieL0ufoDpLsd1Bvhj-hKlE_ExXY?usp=sharing 

(aligned using minimap2 w/ splice:hq preset to a genome that is currently still under embargo, so I cannot share the genome fasta unfortunately!)

**Comment by mourisl** [comment] 2024-11-07 18:11
Thank you! I haven't tested PsiCLASS on minimap2's bam file yet. I'll take a look these days.

**Comment by mbeavitt** [comment] 2024-11-08 12:28
I've inspected the coredump and this was the function call that triggered the stack smashing abort:

```
#8  0x00000000004049c1 in CompareJunctions (startLocation=21188448,
    cigar=0x42a925 <col+40965> "6S14M1I10M1I15M2I13M1I5M2I6M1I5M1I7M3I7M2I7M1I5M1I10M1I17M2I16M2I10M1I9M2I20M1I10M2I8M1I16M5I30M1I3M2I7M2I6M2I5M1I5M1I4M1I6M3I15M2I29M2I11M1I5M1I5M1I4M1I10M2I22M1I5M3I6M2I3M1I4M1I12M1I13M1I8M1
I6M2I3M1"...) at FindJunction.cpp:725
```

**Comment by mbeavitt** [comment] 2024-11-08 12:59
I've noticed that the ccnt variable ends up being 1128 in the CompareJunctions function that causes the crash - could this be causing an out of bounds array dereference by indexing the cigarSeg array?

**Comment by mbeavitt** [comment] 2024-11-08 13:01
Changing the cigarSeg size to 2000 fixes the issue :) 

I've created a pull request.

**Comment by mbeavitt** [comment] 2024-11-08 13:07
Is it worth using dynamic allocation to prevent further issues with long reads? I imagine this would probably fail if ONT was used.

**Comment by mourisl** [comment] 2024-11-08 15:36
Yes, moving to dynamic allocation is a good idea. Both the LINE_SIZE for storing the read information and segcount should be dynamic. I'm not actively working on reference-based transcriptome assembly nowadays, but I'll try to patch the code in the next week or two.

**Comment by mbeavitt** [comment] 2024-11-08 15:42
No problem, tbh I am happy to work on this if you don't mind reviewing my PRs! I would love to contribute.

**Comment by mourisl** [comment] 2024-11-08 16:02
That would be great! I had a plan to use "alignments.hpp" class for FindJunctions.cpp, which has a better wrapper for SAM/BAM file, and at least resolves the LINE_SIZE issue. This class also assumes a maximum number of segments, but the "segments" can be easily changed into a std::vector.

**Comment by mbeavitt** [comment] 2024-11-08 16:19
As a quick side note, since this thread is about long reads in general, do you think that the complexity filtering step in `junc` is still suitable for long reads? I don't know if there are any assumptions about read length in this stage.

**Comment by mourisl** [comment] 2024-11-08 16:28
> As a quick side note, since this thread is about long reads in general, do you think that the complexity filtering step in `junc` is still suitable for long reads? I don't know if there are any assumptions about read length in this stage.

Which specific step do you mean? Is it the filtering within junc, or after running junc (the get trusted splice site step)?

**Comment by mbeavitt** [comment] 2024-11-08 16:59
lines 559-560 and 578-579:
```
if ( max > 0.8 * sum )
    validRead = false ;
```

My understanding is that this is filtering based on the relative occurrence of different CIGAR characters (S/M/I/N). I was wondering if you thought that the constant 0.8 was similarly true for short and long reads.

**Comment by mbeavitt** [comment] 2024-11-08 20:37
hmm, I think there are more issues with the long reads. A call to subexon-info appears to get stuck in an infinite loop at this section:

https://github.com/splicebox/PsiCLASS/blob/bcebe773a26119108a382952252df03c5c872809/blocks.hpp#L862-L891

**Comment by mourisl** [comment] 2024-11-08 20:58
> you

That filter should be fine for long reads. It test whether this is a low-complexity reads, like more than 80% of the sequence is of the one type of nucleotide. 

> hmm, I think there are more issues with the long reads. 

I think so..there might be multiple places with some fixed array size for exons..

**Comment by mbeavitt** [comment] 2024-11-26 11:58
@mourisl could you review this PR?

**Closed** 2024-11-26 16:04 UTC
